services:
  server:
    build: .
    ports:
      - 8080:8080
    command: ["./app", "--worker=false"]

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: uptime_monitor
      LOG_LEVEL: info
      APP_ENV: development
      TEMPORAL_TASK_QUEUE: ping-task-queue
      TEMPORAL_WORKFLOW_NAME: ping-workflow
      TEMPORAL_HOST: host.docker.internal:7233
      REDIS_ADDR: redis:6379
      REDIS_DB: "0"

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  worker:
    build: .
    command: ["./app", "--server=false"]

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: uptime_monitor
      LOG_LEVEL: info
      APP_ENV: development
      TEMPORAL_TASK_QUEUE: ping-task-queue
      TEMPORAL_WORKFLOW_NAME: ping-workflow
      TEMPORAL_HOST: host.docker.internal:7233
      REDIS_ADDR: redis:6379
      REDIS_DB: "0"

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    image: redis:8-alpine

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: "redis-server --appendonly yes"

  postgres:
    image: postgres:17-alpine

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: uptime_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uptime_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/temporal:latest

    ports:
      - 7233:7233
      - 8233:8233

    volumes:
      - temporal-data:/home/temporal

    command: server start-dev --ip 0.0.0.0 --db-filename /home/temporal/temporal.db

volumes:
  temporal-data:
  postgres-data:
  redis_data:
