syntax = "proto3";

package ping.v1;

option go_package = "github.com/minhnbnt/uptime-monitor-microservices/common/proto/generated/ping/v1;pingv1";

enum PingType {
  PING_TYPE_POD_STATUS = 0;
  PING_TYPE_HTTP_DNS = 1;
}

message HttpDnsConfig {
  int32 port = 1;
  string endpoint_path = 2;
  int32 expected_code = 3;
  string body_check_expr = 4;
  string method = 5;
}

message PingRequest {
  string namespace = 1;
  string kind = 2;
  string object_id = 3;
  string container_name = 4;
  int64 timeout_ms = 5;
  PingType ping_type = 6;
  optional HttpDnsConfig http_dns_config = 7;
}

message PingResponse {
  bool running = 1;
  string error = 2;
}

service PingService {
  rpc Ping(PingRequest) returns (PingResponse);
}
