{{- if .Values.cilium.enabled }}
{{- $ns := include "uptime-monitor.namespace" . -}}
{{- $ext := .Values.global.externalHost -}}

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: {{ $ns }}
spec:
  endpointSelector: {}
  ingress: []
  egress: []

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ $ns }}
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-apiserver
  namespace: {{ $ns }}
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - kube-apiserver

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: auth-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    - matchLabels:
        app.kubernetes.io/name: notification-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "auth-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toCIDR:
    - {{ $ext }}/32
    toPorts:
    - ports:
      - port: "6432"
        protocol: TCP
      - port: "6379"
        protocol: TCP

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: server-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: server-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ping-service
    - matchLabels:
        app.kubernetes.io/name: ontime-service
    - matchLabels:
        app.kubernetes.io/name: importer-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toCIDR:
    - {{ $ext }}/32
    toPorts:
    - ports:
      - port: "6432"
        protocol: TCP
      - port: "6379"
        protocol: TCP
      - port: "7233"
        protocol: TCP
      - port: "1025"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ping-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ping-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ontime-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ontime-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ping-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ping-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ping-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toEntities:
    - world
  - toCIDR:
    - {{ $ext }}/32
    toPorts:
    - ports:
      - port: "6379"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ontime-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ontime-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ontime-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ontime-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ontime-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ping-service
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ontime-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toCIDR:
    - {{ $ext }}/32
    toPorts:
    - ports:
      - port: "6432"
        protocol: TCP
      - port: "6379"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: importer-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: importer-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "importer-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: notification-service
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "notification-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "notification-service" "grpcPort" }}"
        protocol: TCP
      rules:
        http: [{}]
  egress:
  - toCIDR:
    - {{ $ext }}/32
    toPorts:
    - ports:
      - port: "6432"
        protocol: TCP
      - port: "7233"
        protocol: TCP
      - port: "1025"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: auth-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "auth-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: server-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "server-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ontime-service
    toPorts:
    - ports:
      - port: "{{ index .Values.apps "ontime-service" "port" }}"
        protocol: TCP
      rules:
        http: [{}]

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: traefik
  namespace: {{ $ns }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  ingress:
  - fromEntities:
    - world
  egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/part-of: uptime-monitor

{{- end }}
