db:
  host: pgbouncer
  port: 6432
  user: server
  password: server
  dbname: server

redis:
  addr: redis:6379
  password: ""
  db: 0

log:
  level: info

grpc:
  port: "50051"
  server_addr: "localhost:50051"
  event_addr: ontime:50052
