{{- $ns := include "uptime-monitor.namespace" . -}}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secrets
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: uptime-monitor
type: Opaque
stringData:
  {{- toYaml $secret | nindent 2 }}
{{- end }}
