debezium:
  source:
    connector:
      class: io.debezium.connector.postgresql.PostgresConnector

    offset:
      storage: io.debezium.storage.redis.offset.RedisOffsetBackingStore

    database:
      hostname: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: server

    topic:
      prefix: uptime

    table:
      include:
        list: public.endpoints, public.servers

    plugin:
      name: pgoutput

  sink:
    type: redis
    redis:
      address: redis:6379
      message:
        format: extended

quarkus:
  log:
    console:
      json:
        enabled: false
