server:
  port: 8085

temporal:
  host: temporal:7233
  workflow_name: send-report
  digest_task_queue: digest-task-queue

mail:
  smtp_host: mailpit
  smtp_port: 1025
  from_address: noreply@uptime-monitor.local
  disable_security: true
  tls_insecure_skip_verify: false

log:
  level: debug

auth:
  issuer: http://gotrue:9999
  service_token: ${AUTH_SERVICE_TOKEN}

grpc:
  server_addr: "server-service:50051"
  event_addr: "ontime-service:50052"

digest:
  max_records: 10000
