redis:
  addr: redis:6379
  password: ""
  db: 0

server:
  port: 8083

grpc:
  server_addr: server-service:50051
  event_addr: ontime-service:50052
  ping_port: "50053"

log:
  level: info

scheduler:
  backend: redis
