redis:
  addr: redis:6379
  password: ""
  db: 0

  scheduler_shards: 10
  scheduler_claim_limit: 50

server:
  port: 8083

grpc:
  port: "50053"
  server_addr: server-service:50051
  event_addr: ontime-service:50052

log:
  level: info

scheduler:
  backend: redis
