db:
  host: pgbouncer
  port: 6432
  user: postgres
  password: postgres
  dbname: uptime_monitor

redis:
  addr: redis:6379
  password: ""
  db: 0

server:
  port: 8083

grpc:
  server_addr: server:50051

log:
  level: info

scheduler:
  backend: redis
